---
title: "putting data"
output: html_notebook
---



# individual scores
```{r}
library(tidyverse)

## import raw scoring data from gsheet 'Disc Putting Scorecard_BH1 (Responses)'
#install.packages("googlesheets4")
library(googlesheets4)
a <- read_sheet("https://docs.google.com/spreadsheets/d/1zsM6NH5NoT_QI7be9z1VnkurByc9DsmGCzeoomI5AoY/edit#gid=184111277")
gsraw <- as.data.frame(a)
names(gsraw) <- make.names(names(gsraw))


circle2s <- read_sheet("https://docs.google.com/spreadsheets/d/1qmQB_rLHvEdNmKP3omnVYM2yn5UlibUx3y-WmrSZij8/edit#gid=1610389370", sheet = "circle2s")


## tidy << wrangle
### solo rounds
tidySolo <- gsraw %>%
  filter(grepl("solo", Game.style)) %>% 
  mutate(player = if_else(PlayerID == "OTHER_WRITE_IN",
                          paste0("WRITE_IN", home.solo.WRITE.IN.nickname.number), 
                          PlayerID)) %>% 
  mutate(position = "solo") %>% 
  mutate(course=Putting.Course) %>% 
  #select(course=Putting.Course, Timestamp, Game.style, position, Purpose, Outcome, Special.Notes, player, starts_with("solo.putts.made"))  %>% 
  pivot_longer(c("solo.putts.made..hole1.", "solo.putts.made..hole2.", 
"solo.putts.made..hole3.", "solo.putts.made..hole4.", "solo.putts.made..hole5.", 
"solo.putts.made..hole6.", "solo.putts.made..hole7.", "solo.putts.made..hole8.", 
"solo.putts.made..hole9.", "solo.putts.made..hole10.", "solo.putts.made..hole11.", 
"solo.putts.made..hole12.", "solo.putts.made..hole13.", "solo.putts.made..hole14.", 
"solo.putts.made..hole15.", "solo.putts.made..hole16.", "solo.putts.made..hole17.", 
"solo.putts.made..hole18."), names_to = "hole", values_to = "result") %>% 
  mutate(hole = as.integer(gsub("solo.putts.made..hole", "", hole))) %>% 
  mutate(putts.made = if_else(is.na(result), 0, 
                              ifelse(result == "putt made", 1, 999))) %>%
  left_join(circle2s, by = c("course", "hole")) %>% 
  mutate(circle2 = if_else(is.na(circle2), 0, 1)) %>% 
  mutate(score = if_else(putts.made == 0, 0, 
                         ifelse(putts.made == 1, 1+circle2, 999))) %>% 
  select(course, Timestamp, Game.style, position, Purpose, Outcome, Special.Notes, player, hole, putts.made, score)

roundsSolo <- tidySolo %>% 
group_by(course, player, Timestamp) %>% 
summarise_at(.,vars(putts.made, score), 
              funs(sum(., na.rm = TRUE))) %>% 
  arrange(desc(score))



### 1-on-1 (h2h) rounds part1:  home player
tidy1on1_home <- gsraw %>% filter(Game.style == "1-on-1") %>% 
  mutate(player = if_else(Home == "OTHER_WRITE_IN",
                          paste0("WRITE_IN", home.solo.WRITE.IN.nickname.number), 
                          Home)) %>% 
  mutate(position = "home") %>% 
  mutate(course=Putting.Course) %>% 
  #select(starts_with("h2h."))  %>% 
  pivot_longer(c( "h2h.putts.made..hole1.", 
"h2h.putts.made..hole2.", "h2h.putts.made..hole3.", "h2h.putts.made..hole4.", 
"h2h.putts.made..hole5.", "h2h.putts.made..hole6.", "h2h.putts.made..hole7.", 
"h2h.putts.made..hole8.", "h2h.putts.made..hole9.", "h2h.putts.made..hole10.", 
"h2h.putts.made..hole11.", "h2h.putts.made..hole12.", "h2h.putts.made..hole13.", 
"h2h.putts.made..hole14.", "h2h.putts.made..hole15.", "h2h.putts.made..hole16.", 
"h2h.putts.made..hole17.", "h2h.putts.made..hole18."), names_to = "hole", values_to = "result") %>% 
  mutate(hole = as.integer(gsub("h2h.putts.made..hole", "", hole))) %>% 
  mutate(putts.made = if_else(is.na(result), 0, 
                              ifelse(grepl("home", result)==TRUE, 1, 0))) %>%
  left_join(circle2s, by = c("course", "hole")) %>% 
  mutate(circle2 = if_else(is.na(circle2), 0, 1)) %>% 
  mutate(score = if_else(putts.made == 0, 0, 
                         ifelse(putts.made == 1, 1+circle2, 999))) %>% 
  select(course, Timestamp, Game.style, position, Purpose, Outcome, Special.Notes, player, hole, putts.made, score)

dput(names(tidy1on1_home))



### 1-on-1 (h2h) rounds part2:  visiting player
tidy1on1_visitor <- gsraw %>% filter(Game.style == "1-on-1") %>% 
  mutate(player = if_else(Visitor == "OTHER_WRITE_IN",
                          paste0("WRITE_IN", visitor.player2.WRITE.IN.nickname.number), 
                          Visitor)) %>% 
  mutate(position = "visitor") %>% 
  mutate(course=Putting.Course) %>% 
  #select(starts_with("h2h."))  %>% 
  pivot_longer(c( "h2h.putts.made..hole1.", 
"h2h.putts.made..hole2.", "h2h.putts.made..hole3.", "h2h.putts.made..hole4.", 
"h2h.putts.made..hole5.", "h2h.putts.made..hole6.", "h2h.putts.made..hole7.", 
"h2h.putts.made..hole8.", "h2h.putts.made..hole9.", "h2h.putts.made..hole10.", 
"h2h.putts.made..hole11.", "h2h.putts.made..hole12.", "h2h.putts.made..hole13.", 
"h2h.putts.made..hole14.", "h2h.putts.made..hole15.", "h2h.putts.made..hole16.", 
"h2h.putts.made..hole17.", "h2h.putts.made..hole18."), names_to = "hole", values_to = "result") %>% 
  mutate(hole = as.integer(gsub("h2h.putts.made..hole", "", hole))) %>% 
  mutate(putts.made = if_else(is.na(result), 0, 
                              ifelse(grepl("visitor", result)==TRUE, 1, 0))) %>%
  left_join(circle2s, by = c("course", "hole")) %>% 
  mutate(circle2 = if_else(is.na(circle2), 0, 1)) %>% 
  mutate(score = if_else(putts.made == 0, 0, 
                         ifelse(putts.made == 1, 1+circle2, 999))) %>% 
  select(course, Timestamp, Game.style, position, Purpose, Outcome, Special.Notes, player, hole, putts.made, score)

dput(names(tidy1on1_visitor))





### 3way rounds rounds part1 of 3:  home player (aka player1)
tidy3way_player1 <- gsraw %>% filter(Game.style == "3way") %>% 
  mutate(player = if_else(player1 == "OTHER_WRITE_IN",
                          paste0("WRITE_IN", home.solo.WRITE.IN.nickname.number), 
                          player1)) %>% 
  mutate(position = "player1") %>% 
  mutate(course=Putting.Course) %>% 
  #select(starts_with("X3way."))  %>% 
  pivot_longer(c("X3way.putts.made..hole1.", "X3way.putts.made..hole2.", "X3way.putts.made..hole3.", 
"X3way.putts.made..hole4.", "X3way.putts.made..hole5.", "X3way.putts.made..hole6.", 
"X3way.putts.made..hole7.", "X3way.putts.made..hole8.", "X3way.putts.made..hole9.", 
"X3way.putts.made..hole10.", "X3way.putts.made..hole11.", "X3way.putts.made..hole12.", 
"X3way.putts.made..hole13.", "X3way.putts.made..hole14.", "X3way.putts.made..hole15.", 
"X3way.putts.made..hole16.", "X3way.putts.made..hole17.", "X3way.putts.made..hole18."), names_to = "hole", values_to = "result") %>% 
  mutate(hole = as.integer(gsub("X3way.putts.made..hole", "", hole))) %>% 
  mutate(putts.made = if_else(is.na(result), 0, 
                              ifelse(grepl("player1", result)==TRUE, 1, 0))) %>%
  left_join(circle2s, by = c("course", "hole")) %>% 
  mutate(circle2 = if_else(is.na(circle2), 0, 1)) %>% 
  mutate(score = if_else(putts.made == 0, 0, 
                         ifelse(putts.made == 1, 1+circle2, 999))) %>% 
  select(course, Timestamp, Game.style, position, Purpose, Outcome, Special.Notes, player, hole, putts.made, score)

dput(names(tidy3way_player1))




### 3way rounds rounds part2 of3:  player2
tidy3way_player2 <- gsraw %>% filter(Game.style == "3way") %>% 
  mutate(player = if_else(player2 == "OTHER_WRITE_IN",
                          paste0("WRITE_IN", visitor.player2.WRITE.IN.nickname.number), 
                          player2)) %>% 
  mutate(position = "player2") %>% 
  mutate(course=Putting.Course) %>% 
  #select(starts_with("X3way."))  %>% 
  pivot_longer(c("X3way.putts.made..hole1.", "X3way.putts.made..hole2.", "X3way.putts.made..hole3.", 
"X3way.putts.made..hole4.", "X3way.putts.made..hole5.", "X3way.putts.made..hole6.", 
"X3way.putts.made..hole7.", "X3way.putts.made..hole8.", "X3way.putts.made..hole9.", 
"X3way.putts.made..hole10.", "X3way.putts.made..hole11.", "X3way.putts.made..hole12.", 
"X3way.putts.made..hole13.", "X3way.putts.made..hole14.", "X3way.putts.made..hole15.", 
"X3way.putts.made..hole16.", "X3way.putts.made..hole17.", "X3way.putts.made..hole18."), names_to = "hole", values_to = "result") %>% 
  mutate(hole = as.integer(gsub("X3way.putts.made..hole", "", hole))) %>% 
  mutate(putts.made = if_else(is.na(result), 0, 
                              ifelse(grepl("player2", result)==TRUE, 1, 0))) %>%
  left_join(circle2s, by = c("course", "hole")) %>% 
  mutate(circle2 = if_else(is.na(circle2), 0, 1)) %>% 
  mutate(score = if_else(putts.made == 0, 0, 
                         ifelse(putts.made == 1, 1+circle2, 999))) %>% 
  select(course, Timestamp, Game.style, position, Purpose, Outcome, Special.Notes, player, hole, putts.made, score)





### 3way rounds rounds part2 of3:  player2
tidy3way_player3 <- gsraw %>% filter(Game.style == "3way") %>% 
  mutate(player = if_else(player3 == "OTHER_WRITE_IN",
                          paste0("WRITE_IN", player3.WRITE.IN.nickname.number), 
                          player3)) %>% 
  mutate(position = "player3") %>% 
  mutate(course=Putting.Course) %>% 
  #select(starts_with("X3way."))  %>% 
  pivot_longer(c("X3way.putts.made..hole1.", "X3way.putts.made..hole2.", "X3way.putts.made..hole3.", 
"X3way.putts.made..hole4.", "X3way.putts.made..hole5.", "X3way.putts.made..hole6.", 
"X3way.putts.made..hole7.", "X3way.putts.made..hole8.", "X3way.putts.made..hole9.", 
"X3way.putts.made..hole10.", "X3way.putts.made..hole11.", "X3way.putts.made..hole12.", 
"X3way.putts.made..hole13.", "X3way.putts.made..hole14.", "X3way.putts.made..hole15.", 
"X3way.putts.made..hole16.", "X3way.putts.made..hole17.", "X3way.putts.made..hole18."), names_to = "hole", values_to = "result") %>% 
  mutate(hole = as.integer(gsub("X3way.putts.made..hole", "", hole))) %>% 
  mutate(putts.made = if_else(is.na(result), 0, 
                              ifelse(grepl("player3", result)==TRUE, 1, 0))) %>%
  left_join(circle2s, by = c("course", "hole")) %>% 
  mutate(circle2 = if_else(is.na(circle2), 0, 1)) %>% 
  mutate(score = if_else(putts.made == 0, 0, 
                         ifelse(putts.made == 1, 1+circle2, 999))) %>% 
  select(course, Timestamp, Game.style, position, Purpose, Outcome, Special.Notes, player, hole, putts.made, score)


tidyScores <- rbind(tidy1on1_home, tidy1on1_visitor) %>% 
  rbind(., tidy3way_player1) %>% 
  rbind(., tidy3way_player2) %>% 
  rbind(., tidy3way_player3) %>% 
  rbind(., tidySolo)  %>% 
  arrange(desc(Timestamp))

individualRounds <- tidyScores %>% 
group_by(course, player, Timestamp, Game.style, position, Purpose, Outcome) %>% 
summarise_at(.,vars(putts.made, score), 
              funs(sum(., na.rm = TRUE))) %>% 
  mutate(circle2s = score-putts.made) %>% 
  mutate(lastUpdated = Sys.time()) %>% 
  arrange(desc(score)) %>% 
  select(player, score, circle2s, putts.made, everything())


write_sheet(individualRounds, ss = "https://docs.google.com/spreadsheets/d/1zsM6NH5NoT_QI7be9z1VnkurByc9DsmGCzeoomI5AoY/edit#gid=2095346489", sheet = "individualRounds")




holeSummary <- tidyScores %>% 
group_by(course, hole) %>% 
summarise_at(.,vars(putts.made), 
              funs(n(), sum(., na.rm = TRUE))) %>%
  mutate(attempts = n, made = sum) %>%
  mutate(madePct =round(100*(made/attempts), 1)) %>% 
  select(course, hole, attempts, made, madePct) %>% 
  mutate(lastUpdated = Sys.time())

write_sheet(holeSummary, ss = "https://docs.google.com/spreadsheets/d/1zsM6NH5NoT_QI7be9z1VnkurByc9DsmGCzeoomI5AoY/edit#gid=2095346489", sheet = "holeSummary")


```



## Team scores
```{r}
### TEAM rounds
df.h2h <- gsraw %>% filter(Game.style == "2-on-2")
```

